version: "3"

services:
  db:
    image: "mysql:8.0.32"
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - ./dbdata:/var/lib/mysql/:delegated
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

  php-fpm:
    container_name: base_backend
    build:
      context: ../backend
      dockerfile: ../docker/dockerfiles/backend
    volumes:
      - ../backend:/var/www/html
      # - ./php.conf:/usr/local/etc/php/conf.d
    networks:
      - my_network

  nginx:
    container_name: base_nginx
    build:
      context: ../backend
      dockerfile: ../docker/dockerfiles/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../backend:/var/www/html
      - ./nginx.conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/resource/ssl
    networks:
      - my_network

networks:
  my_network:
